### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by yuifu** [huangyh09/brie#1]
I had an error when I test `brie`.

How can I install and use BRIE?

- python 3.6.0 (docker/python:3.6.0)

```
$ brie
Traceback (most recent call last):
  File "/usr/local/bin/brie", line 11, in <module>
    load_entry_point('brie==0.1.1', 'console_scripts', 'brie')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/brie/brie.py", line 13, in <module>
    from utils.gtf_utils import loadgene
ModuleNotFoundError: No module named 'utils'
```

**Comment by huangyh09** [comment]
Thanks for using BRIE. 

The issue comes from the compatibility with Python3. Current version only supports Python2. A new version with fully supporting Python3 will be released soon.

Yuanhua

**Comment by huangyh09** [comment]
Now the new version v0.1.2 has been released with fully supporting Python3, which is available on both GitHub and pypi. See what is new:
https://brie-rna.sourceforge.io/release.html#release-v0-1-2-13-01-2017

Any debugging test is welcome.

Thanks for using BRIE.
Yuanhua
