### ISSUE TITLE
Other AS types counting, no output

### ISSUE THREAD

**Issue by zhaoshuoxp** [huangyh09/brie#45]
Hi Yuanhua,

I am using v2.2 to count other types of AS, A3SS for example: 

brie-count -a ~/genome/mm10/mouseAS/A3SS.gff3 -o . -S bamfile.list -p 8 -t Any

Even with -t Any option, this command still gives error message and stuck like forever:
--------------------------
[BRIE2] example head cells:
[['/..../116434_42_3.bam'
  '116434_42_3']
 ['/..../116434_61_39.bam'
  '116434_61_39']
 ['/..../116434_8_46.bam'
  '116434_8_46']] ...
[BRIE2] loading gene annotations ... Done.
[BRIE2] counting reads for 6104 genes in 3140 sam files with 8 cores...
This is not exon-skipping event!
None
This is not exon-skipping event!
None
This is not exon-skipping event!
None
-------------------------

Did I miss anything or put something wrong?

Many thanks!

Quanyi

**Comment by liuyu988** [comment]
Hi Quanyi，
  Have you sovled this problem?i seem to meet the  problem similar to yours. thanks!

LiuYu

**Comment by zhaoshuoxp** [comment]
> Hi Quanyi， Have you sovled this problem?i seem to meet the problem similar to yours. thanks!
> 
> LiuYu

Not yet.

**Comment by huangyh09** [comment]
Thanks both for trying out the new feature on other splicing types. Sorry it's actually [a minor bug](https://github.com/huangyh09/brie/commit/8f83c566f9d9a614807f6cf0fa80de5f2d283804#diff-700dede44db33e635779597543487317a75d9f312a890adfc6791dfa70fde7e8R104) in the code, as we only tested the other splicing events in droplet data.

Now, it has been fixed to support smart-seq in the new release [v2.2.1](https://pypi.org/project/brie/). Please upgrade your package, e.g., by `pip install -U brie` and try your command line again.

Yuanhua

**Comment by liuyu988** [comment]
> Thanks both for trying out the new feature on other splicing types. Sorry it's actually [a minor bug](https://github.com/huangyh09/brie/commit/8f83c566f9d9a614807f6cf0fa80de5f2d283804#diff-700dede44db33e635779597543487317a75d9f312a890adfc6791dfa70fde7e8R104) in the code, as we only tested the other splicing events in droplet data.
> 
> Now, it has been fixed to support smart-seq in the new release [v2.2.1](https://pypi.org/project/brie/). Please upgrade your package, e.g., by `pip install -U brie` and try your command line again.
> 
> Yuanhua

Thank you for your reply!  Yu

**Comment by zhaoshuoxp** [comment]
> Thanks both for trying out the new feature on other splicing types. Sorry it's actually [a minor bug](https://github.com/huangyh09/brie/commit/8f83c566f9d9a614807f6cf0fa80de5f2d283804#diff-700dede44db33e635779597543487317a75d9f312a890adfc6791dfa70fde7e8R104) in the code, as we only tested the other splicing events in droplet data.
> 
> Now, it has been fixed to support smart-seq in the new release [v2.2.1](https://pypi.org/project/brie/). Please upgrade your package, e.g., by `pip install -U brie` and try your command line again.
> 
> Yuanhua

Thanks! The brie-count now works with -t Any. But brie-quant seems don't recognize the generated  count.h5ad file:
brie-quant -i brie_count.h5ad -o quant.h5ad --interceptMode gene
layers: ['isoform1', 'isoform2', 'ambiguous']
Filtered out 2732 genes with less than 50 total counts or 30 cells with unique counts or 10 unique counts or 0.0010 minor isoform frequency
AnnData object with n_obs × n_vars = 1850 × 0
    obs: 'samID', 'samCOUNT'
    var: 'GeneID', 'GeneName', 'TranLens', 'TranIDs', 'n_counts', 'n_counts_uniq'
    uns: 'event_type'
    varm: 'effLen', 'p_ambiguous'
    layers: 'ambiguous', 'isoform1', 'isoform2', 'poorQual'
2022-07-21 10:23:49.149541: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/gridview//pbs/dispatcher/lib::/usr/local/lib64:/usr/local/lib
2022-07-21 10:23:49.149614: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/usr/local/python3/bin/brie-quant", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.7/site-packages/brie/bin/quant.py", line 219, in main
    options.batch_size, options.pseudo_count, options.test_base)
  File "/usr/local/python3/lib/python3.7/site-packages/brie/bin/quant.py", line 116, in quant
    tau_prior=tau_prior)
  File "/usr/local/python3/lib/python3.7/site-packages/brie/models/model_wrap.py", line 260, in fitBRIE
    ResVal = concate(res_list)
  File "/usr/local/python3/lib/python3.7/site-packages/brie/models/model_wrap.py", line 81, in concate
    res_merge = BRIE_RV_list[0]
IndexError: list index out of range

it might be the issue with n_var, as n_obs × n_vars = 1850 × 0 in the log. While when I actually open count.h5ad with anndata, it has vars:
adata=sc.read_h5ad("./brie_count.h5ad")
adata
AnnData object with n_obs × n_vars = 1850 × 2732
    obs: 'samID', 'samCOUNT'
    var: 'GeneID', 'GeneName', 'TranLens', 'TranIDs'
    uns: 'event_type'
    varm: 'effLen', 'p_ambiguous'
    layers: 'ambiguous', 'isoform1', 'isoform2', 'poorQual'

Any ideas with it? I will be grateful for your help.
Quanyi

**Comment by TuoCai2000** [comment]
Hi Quanyi,
I notice that you use the command brie-count with annotation '/genome/mm10/mouseAS/A3SS.gff3' , can you tell me how to generate it? like intron retension and A3SS.etc
Thank you!

Tuo

**Comment by zhaoshuoxp** [comment]
> Hi Quanyi, I notice that you use the command brie-count with annotation '/genome/mm10/mouseAS/A3SS.gff3' , can you tell me how to generate it? like intron retension and A3SS.etc Thank you!
> 
> Tuo

HI Tuo, I simply use the briekit (https://github.com/huangyh09/briekit/wiki) to generate them from GENCODE GTF file. Please note that the filtering function of it does not work on my end so I just use the unfiltered GFF to proceed.
Quanyi
